[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.2"

[features]
seeds = false
skip-lint = false

[programs.localnet]
blockmesh-program = "CfaL9sdaEK49r4WLAtVh2vVgAZuv2eKbb6jSB5jDCMSF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ohaddahan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/blockmesh-program",
]