# https://github.com/LukeMathWalker/zero-to-production/blob/main/.github/workflows/general.yml
name: CLIPPY
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
env:
  RUSTC_VERSION: 1.75.0
  SQLX_OFFLINE: true
  SQLX_OFFLINE_DIR: .sqlx
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.7.3
  SQLX_FEATURES: "rustls,postgres"
jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: clippy-sqlx-${{ env.SQLX_VERSION }}
          cache-all-crates: true
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      - name: Linting
        run: cargo clippy -- -D warnings