# https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
name: Update Tailwind CSS
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: useblacksmith/setup-node@v5
        with:
          node-version: lts/*
      - name: install
        run: |
          npm install yarn
          yarn install
      - name: Deploy CSS file to R2
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3.55.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./
          preCommands: |
            npx tailwindcss -i ./input.css -o ./tailwind.css
          command: r2 object put assets/tailwind.css --file tailwind.css